project:
  type: website

website:
  title: "OIST Graduation Ball 2026"
  page-footer: "Created with [Quarto](https://quarto.org) by Igors Dubanevics | 2026"

format:
  html:
    theme:
      - quartz
      - custom.scss
    css: styles.css
    toc: false



